version: 0.2

phases:
  pre_build:
    commands:
      - echo "Create connection between Docker and ECR repository (Login)"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Setting version number"
      - VERSION_START="1.1."
      - IMAGE_TAG="${VERSION_START}${CODEBUILD_BUILD_NUMBER}"
      - IMAGE_NAME="${IMAGE_NS}/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_TAG="${REPOSITORY_URI}/${IMAGE_NAME}"
      - echo "Image name is ${IMAGE_NAME}"
      - echo "Repository tag is ${REPOSITORY_TAG}"

  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_NAME ./analytics --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_USERNAME=$DB_USERNAME --no-cache
      - docker tag $IMAGE_NAME $REPOSITORY_TAG  

  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_TAG
