version: 0.2

phases:
  pre_build:
    commands:
      - echo "Create connection between Docker and ECR repository (Login)"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_NS/$IMAGE_REPO_NAME:$IMAGE_TAG ./analytics --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_USERNAME=$DB_USERNAME --no-cache
      - docker tag $IMAGE_NS/$IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NS/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER    
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NS/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER  
